version: 2.1
jobs:
  build:
    docker:
      - image: gmacario/build-aosp
    steps:
      - checkout
      - run:
          command: |
            mkdir -p ./aosp
            cd ./aosp
            repo init -u https://android.googlesource.com/platform/manifest -b android-4.0.1_r1
            repo sync