version: 2.0
jobs:
  build:
    docker:
      - image: gmacario/build-aosp
    steps:
      - checkout
      - run:
          command: |
            git config --global user.name "sample"
            git config --global user.email "sample@gmail.com"
            mkdir -p ./aosp
            cd ./aosp
            repo init -u https://android.googlesource.com/platform/manifest -b android-4.0.1_r1
            repo sync